### ISSUE TITLE
Recommend adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by waded** [wcahealth/ansible-styleguide#1]
As someone who has a suggestion for a new rule in the guide, what should I do to suggest it? Should I spend the time to create PR? Should I open an issue? Complain about it on Twitter? What do the maintainers want? I was looking for CONTRIBUTING.md or similar. https://github.com/blog/1184-contributing-guidelines

**Comment by elloboblanco** [comment]
Methinks this can be closed now

**Comment by waded** [comment]
Yeah we already did this. Thanks for noticing!
