### ISSUE TITLE
Role Declaration section deprecation

### ISSUE THREAD

**Issue by waded** [wcahealth/ansible-styleguide#4]
In practice I find the current "Role Declaration" rule (create a task file named to match the role, then include that file in a main.yml that does nothing else) to be boilerplate-heavy, forcing an include right off the bat to address what's generally an editor issue ("having several main.yml files open at once can get very confusing".) It also encourages a single task file per role, which in larger roles may not be the right structure... as to name a task file otherwise contradicts the role name, so it seems people generally just append more and more to the task file.

I prefer we don't favor boilerplate to fix editor issues in favor of purposeful use of multiple files, so I recommend we strike "Role Declation" in favor of well-documented main.yml, then fragmenting into multiple task .yml files as needed, none of them named the same as the role itself.

**Comment by elloboblanco** [comment]
Seems reasonable to me, :shipit:

**Comment by waded** [comment]
@S3v3nL34fKl0v3r , @warren1011 ?

**Comment by wsutherland-relias** [comment]
This sounds like a good idea to me.

**Comment by brikr** [comment]
This convention was originally proposed by @blakedietz. Maybe he can weigh in on this? I'm okay with the change.

**Comment by blakedietz** [comment]
I think that this change makes sense @waded. You hit the nail on the head as far as

> I prefer we don't favor boilerplate to fix editor issues in favor of purposeful use of multiple files, so I recommend we strike "Role Declation" in favor of well-documented main.yml, then fragmenting into multiple task .yml files as needed, none of them named the same as the role itself.

**Comment by waded** [comment]
Thanks for taking the time to give feedback on this. We'll go with it.
